version: '3.9'

services:
  #web:
  #  build: 
  #      context: ./FilesManagement
  #  ports:
  #    - 80:80
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd0fSA