// <auto-generated />
using Identity.Infra.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Infra.Migrations
{
    [DbContext(typeof(IdentityDBContext))]
    [Migration("20230216191023_AutogeneratedKey")]
    partial class AutogeneratedKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.Infra.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_Password");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usr_UserName");

                    b.HasKey("ID");

                    b.ToTable("fm_User");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            FirstName = "Antoine",
                            LastName = "Hachem",
                            Password = "10|Jf2tWxMCxFxb/UPkHnxZqA==|NsYGhfw4NYyiWLsSxrTISNAB1SYmrinumZTbaBT7wms=",
                            UserId = "8ff7c780-6008-4e8a-9f9f-31e3955d4605",
                            Username = "AntoineH"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
