using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Identity.Infra.Migrations
{
    /// <inheritdoc />
    public partial class AutogeneratedKey : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "fm_User",
                keyColumn: "id",
                keyValue: 1L,
                column: "usr_ID",
                value: "8ff7c780-6008-4e8a-9f9f-31e3955d4605");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "fm_User",
                keyColumn: "id",
                keyValue: 1L,
                column: "usr_ID",
                value: "7d274d1c-1c4c-4ecf-b9aa-c205e749f74d");
        }
    }
}
